---
title: "Resources"
output:
  blogdown::html_page:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

We'll add resources here as they become relevant or we find them. Feel free to send along things you've found useful!

## Getting Started with R

* [RStudio Cloud Guide](https://rstudio.cloud/learn/guide)
* [RStudio Primers](https://rstudio.cloud/learn/primers), 
* [The Tidyverse Style Guide](https://style.tidyverse.org/index.html), suggestions for good coding practices
* [Stata to R::Cheat Sheet](https://mentalbreaks.rbind.io/posts/stata-to-r/)
* [LearnR4Free](https://www.learnr4free.com/)
* [Instructions for installing R, RStudio, and all the tidyverse packages](../install/), if you'd like to have R and RStudio on your own computer.

## Free R Books 
We use a chapter or four from several of these, but you might find other sections useful as well. (Incredibly, this is only a partial list.)

* James Scott. 2021. [Data Science in R: A Gentle Introduction.](https://bookdown.org/jgscott/DSGI/) 
* Hadley Wickham and Garrett Grolemund. 2017. [R for Data science. O’Reilly.](https://r4ds.had.co.nz/) 
* Rafael A. Irizarry. 2021. [Introduction to Data Science.](https://rafalab.github.io/dsbook/) 
* Chester Ismay and Albert Y. Kim. 2021. [Statistical Inference via Data Science: A ModernDive into R and the Tidyverse.](https://moderndive.com/). CRC Press. 
* Bradley Boehmke & Brandon Greenwell. 2021. [Hands-On Machine Learning with R.](https://bradleyboehmke.github.io/HOML/) Routledge. 
* Paul Roback and Julie Legler. 2021. [Beyond Multiple Linear Regression.](https://bookdown.org/roback/bookdown-BeyondMLR/) Routledge.
* Kieran Healy. 2018. [Data Visualization: A Practical Introduction.](https://socviz.co/) Princeton University Press.
* Carson Sievert. 2019. [Interactive web-based data visualization with R, plotly, and shiny.](https://plotly-r.com/) CRC Press. 

## VA Court Processes

* [Ben Schoenfeld's site](https://virginiacourtdata.org/)
* [Virginia's Court System](https://www.vacourts.gov/courts/home.html) web pages
* [VA General District Court Manual](https://www.vacourts.gov/courts/gd/resources/manuals/gdman/gd_manual.pdf)
* [VA Circuit Court Clerk's Manual-Criminal](https://www.vacourts.gov/courts/circuit/resources/manuals/cc_manual_criminal/toc.pdf)
