baseURL: "https://datavis22.mclaibourn.org/"
languageCode: en-us
title: "Data Visualization in R"
theme: mediumish-gohugo-theme
summaryLength: 25
copyright: Michele Claibourn - All rights reserved
enableEmoji: yes
publishDir: docs
params:
  description: LPPP 6500 Fall 2022
  author:
    name: "Professor: Michele Claibourn"
    description: "(Director of Equitable Analysis, UVA Equity Center)"
    thumbnail: images/webimage.png
  index:
    alertbar: no
    mdtext: |
      Wednesdays, August 24-September 21, 7:00-9:30
      
      *Dr. Michele Claibourn (Director of Equitable Analysis, UVA Equity Center and Assistant Professor in Batten)*
      
      **Email: mclaibourn@virginia.edu  |  Office Hours: Tue 12:30-1:30 and by appt.  |  Office: Let's meet outside or on zoom**
    picture: images/webimage.png
    subtitle: LPPP 6500 Fall 2022
    title: "Data Visualization in R"
  logo: images/webimage_small.png
  social:
    github: mclaibourn
    twitter: mclaibourn
    linkedin: mclaibourn
    mail: mclaibourn@virginia.edu

menu:
  main:
    - identifier: syllabus
      name: Syllabus
      url: /static/syllabus
      weight: 100
    - identifier: schedule
      name: Schedule
      url: /static/schedule
      weight: 200
    - identifier: resources
      name: Resources
      url: /static/resources
      weight: 300
    - identifier: slack
      name: Class Slack
      url: https://lppp6500dataviz.slack.com
      weight: 400
    - identifier: projects
      name: Final Projects
      url: /static/projects
      weight: 500
    # - identifer: perusall
    #   name: Perusall
    #   url: https://perusall.com/
    #   weight: 600
#    - identifier: rstudio
#      name: RStudio Cloud
#      url: https://rstudio.cloud/
#      weight: 700
    - identifier: policy
      name: Batten Policies
      url: /static/policy
      weight: 800

markup:
  goldmark:
    renderer:
      unsafe: true
